# Top-level configuration
name = "study-backend"
main = "index.ts"
compatibility_date = "2025-02-10"

workers_dev = false
route = { pattern = "study-backend.ibaguette.com/*", zone_name = "ibaguette.com" }


[[r2_buckets]]
binding = 'resources_bucket'
bucket_name = 'study-storage'



# Production d1_database
[[d1_databases]]
binding = "resources_db"
database_name = "resources-db"
database_id = "3d9ef277-18ee-4b6c-9266-b8cef6d2ea35"

[vars]
ENVIRONMENT_MODE = "production"



# DEVELOPMENT ENVIRONMENT - run with 'npx wrangler dev --env dev'
[env.dev]
[[env.dev.r2_buckets]]
binding = 'resources_bucket'
bucket_name = 'study-storage'

[[env.dev.d1_databases]]
binding = "resources_db"
database_name = "resources-db-DEV"
database_id = "a0fde410-1351-41e3-b746-e724e48ea2ac"

[env.dev.vars]
ENVIRONMENT_MODE = "development"